# Generated by Django 4.1.3 on 2022-11-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_name_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='value',
            field=models.TextField(),
        ),
    ]
