# Generated by Django 4.1.3 on 2022-11-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_specification_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='specification',
            unique_together={('specification_category', 'name')},
        ),
    ]
