# Generated by Django 4.1.3 on 2022-11-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_image_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='stores/'),
        ),
    ]
