# Generated by Django 4.1.3 on 2022-11-29 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_store'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name', '-price')},
        ),
    ]
